spring:
  application:
    name: redis-service

  redis:
    port: 6379
    password: konara
    host: localhost

logging:
  file:
    path: redis-service/logs
  level:
    kg.alymzhan.petchatgpt: DEBUG